use_frameworks!

platform :ios, '9.0'

target 'FPCommentsModule_Example' do
  pod 'FPCommentsModule', :path => '../'
#  pod 'HPGrowingTextView'
  pod 'FPRefresh'

  target 'FPCommentsModule_Tests' do
    inherit! :search_paths

    
  end
end
